"""Build a single-file Kaggriculture agent that routes by player seat.

The two source agents are compressed into isolated namespaces so their module
globals and per-game state cannot collide.  This is useful for online-derived
seat specialisation while keeping Kaggle's required one-file entry point.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import zlib
from pathlib import Path


TEMPLATE = '''"""Seat-routed Kaggriculture submission generated by build_seat_hybrid.py."""
import base64
import zlib


def _load_agent(payload, module_name):
    namespace = {{"__name__": module_name}}
    source = zlib.decompress(base64.b85decode(payload)).decode("utf-8")
    exec(compile(source, module_name, "exec"), namespace)
    return namespace["agent"]


_SEAT0_AGENT = _load_agent({seat0_payload!r}, "_kaggriculture_seat0")
_SEAT1_AGENT = _load_agent({seat1_payload!r}, "_kaggriculture_seat1")


def _player(obs):
    if isinstance(obs, dict):
        value = obs.get("player", 0)
    else:
        getter = getattr(obs, "get", None)
        value = getter("player", 0) if callable(getter) else getattr(obs, "player", 0)
    return 1 if int(value or 0) == 1 else 0


def agent(obs, configuration=None):
    del configuration
    selected = _SEAT1_AGENT if _player(obs) == 1 else _SEAT0_AGENT
    return selected(obs)


__version__ = {version!r}
'''


def encode_source(path: Path) -> str:
    source = path.read_bytes()
    compile(source, str(path), "exec")
    return base64.b85encode(zlib.compress(source, level=9)).decode("ascii")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("seat0_agent", type=Path)
    parser.add_argument("seat1_agent", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--version", default="E329-seat0-wool-near-seat1-tetsutani-v16")
    args = parser.parse_args()

    source = TEMPLATE.format(
        seat0_payload=encode_source(args.seat0_agent),
        seat1_payload=encode_source(args.seat1_agent),
        version=args.version,
    )
    compile(source, str(args.output), "exec")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(source, encoding="utf-8")

    report = {
        "output": str(args.output.resolve()),
        "version": args.version,
        "seat0": {
            "path": str(args.seat0_agent.resolve()),
            "sha256": sha256(args.seat0_agent),
        },
        "seat1": {
            "path": str(args.seat1_agent.resolve()),
            "sha256": sha256(args.seat1_agent),
        },
        "output_sha256": sha256(args.output),
        "output_bytes": args.output.stat().st_size,
    }
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
